version: '3'

services:

  # Events creator, push to collector
  faker:
    container_name: data-engineer_faker
    image: local/data-engineer-faker
    build:
      context: ./faker
      dockerfile: Dockerfile
    depends_on:
      - collector
    environment:
      COLLECTOR_HOST: collector
      COLLECTOR_PORT: 8080
    networks:
      - data-engineer_network
    volumes:
      - ./faker/app:/code/app

  # Events consumer, put into queue
  collector:
    container_name: data-engineer_collector
    image: docker.elastic.co/logstash/logstash-oss:8.3.3
    hostname: collector
    depends_on:
      - broker
    networks:
      - data-engineer_network
    volumes:
      - ./logstash-recorder.conf:/logstash.conf
    command: logstash -f /logstash.conf
    ports:
      - "8080:8080"

  # Queue
  # Kafka manager
  zookeeper:
    container_name: data-engineer_zookeeper
    image: confluentinc/cp-zookeeper:7.2.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - data-engineer_network

  # Kafka broker
  broker:
    container_name: data-engineer_broker
    image: confluentinc/cp-kafka:7.2.1
    hostname: broker
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - data-engineer_network
    ports:
      - "9092:9092"

  # Compute events
  spark:
    container_name: data-engineer_spark
    image: local/data-engineer-spark
    build:
      context: spark/
    hostname: spark
    environment:
      PYSPARK_PYTHON: python3
      DOMAIN: dev.famoco.com
      ATNA_DB_HOST: localhost
      ATNA_DB_NAME: postgres
      ATNA_DB_USERNAME: admin
      ATNA_DB_PASSWORD: admin
    networks:
      - data-engineer_network
    volumes:
      - .:/src/
    tty: true
    stdin_open: true
    restart: unless-stopped
    command: bash

  # SQL database
  sql:
    hostname: sql
    container_name: data-engineer_sql
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
    volumes:
      - data-engineer_sql-data:/var/lib/postgresql/data
    networks:
      - data-engineer_network
    ports:
      - '5432:5432'

networks:
  data-engineer_network:
volumes:
  data-engineer_sql-data: