apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-deployment
  labels:
    app: zookeeper
spec:
  replicas: 1
  selector:
    mactchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zoo1
        image: confluentinc/cp-zookeeper:7.2.1
        ports:
        - containerPort: 2181
      env:
      - name: ZOOKEEPER_CLIENT_PORT
        vale: "1"
      - name: ZOOKEEPER_SERVER_1
        value : zoo1