global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "kafka"
    static_configs:
      - targets: ["kafka-exporter:9308"]
  - job_name: "faker"
    static_configs:
      - targets: ["faker:8000"]