version: "3.8"

services:

  generator:
    image: generator
    container_name: generator
    volumes:
      - ${PWD}/microservices/generator/:/code/app/
      - ${PWD}/k8s/generator/local_docker.env:/code/k8s/generator/.env
    command: python3 app/main.py